import MockAdapter from 'axios-mock-adapter';
import $api from './index'

const mock = new MockAdapter($api);

mock.onGet(`/assets/?data_check_string=erfvd&telegram_user_id=1&received_hash=erfve`).reply(200, {
    message: [
        {
            id: 0,
            currency: 'USD',
            total_sum: 100,
            full_name: 'Bitcoin',
            number: 10,
            name: 'BTC',
            daily_pnl: '15.45',
            transaction_date: '2024-05-24',
            created_at: '2024-05-24',
            updated_at: '2024-05-24',
        },
        {
            id: 1,
            currency: 'USD',
            total_sum: 50,
            full_name: 'Ethereum',
            number: 5,
            name: 'ETH',
            daily_pnl: '7.20',
            transaction_date: '2024-05-24',
            created_at: '2024-05-24',
            updated_at: '2024-05-24',
        },
        {
            id: 2,
            currency: 'USD',
            total_sum: 75,
            full_name: 'Litecoin',
            number: 15,
            name: 'LTC',
            daily_pnl: '3.80',
            transaction_date: '2024-05-24',
            created_at: '2024-05-24',
            updated_at: '2024-05-24',
        },
        {
            id: 2,
            currency: 'USD',
            total_sum: 75,
            full_name: 'Litecoin',
            number: 15,
            name: 'LTC',
            daily_pnl: '3.80',
            transaction_date: '2024-05-24',
            created_at: '2024-05-24',
            updated_at: '2024-05-24',
        },
        {
            id: 2,
            currency: 'USD',
            total_sum: 75,
            full_name: 'Litecoin',
            number: 15,
            name: 'LTC',
            daily_pnl: '3.80',
            transaction_date: '2024-05-24',
            created_at: '2024-05-24',
            updated_at: '2024-05-24',
        },
        {
            id: 2,
            currency: 'USD',
            total_sum: 75,
            full_name: 'Litecoin',
            number: 15,
            name: 'LTC',
            daily_pnl: '3.80',
            transaction_date: '2024-05-24',
            created_at: '2024-05-24',
            updated_at: '2024-05-24',
        },
        {
            id: 2,
            currency: 'USD',
            total_sum: 75,
            full_name: 'Litecoin',
            number: 15,
            name: 'LTC',
            daily_pnl: '3.80',
            transaction_date: '2024-05-24',
            created_at: '2024-05-24',
            updated_at: '2024-05-24',
        },
        {
            id: 2,
            currency: 'USD',
            total_sum: 75,
            full_name: 'Litecoin',
            number: 15,
            name: 'LTC',
            daily_pnl: '3.80',
            transaction_date: '2024-05-24',
            created_at: '2024-05-24',
            updated_at: '2024-05-24',
        },
    ],

});

